---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azure-disk
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: managed
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-default-pvc
  labels:
    app: mysqlpvc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysqlpvc
  template:
    metadata:
      labels:
        app: mysqlpvc
        version: v1.0
    spec:
      containers:
        - image: khaleel.jfrog.io/mydocker/mysqlnew:1.0
          name: mysqlpvc
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: rootroot
            - name: MYSQL_DATABASE
              value: kpmysqldb
            - name: MYSQL_USER
              value: root
            - name: MYSQL_PASSWORD
              value: rootroot
          volumeMounts:
            - name: mysqldbdefault
              mountPath: /var/lib/mysql
          ports:
            - containerPort: 3306
      imagePullSecrets:
        - name: artregcred 
      volumes:
        - name: mysqldbdefault
          persistentVolumeClaim:
            claimName: azure-disk